// register
export const FETCH_REGISTER= 'FETCH_REGISTER';
export const FETCH_REGISTER_SUCCESS= 'FETCH_REGISTER_SUCCESS'
export const FETCH_REGISTER_FAILED= 'FETCH_REGISTER_FAILED'

// login
export const FETCH_LOGIN= 'FETCH_LOGIN';
export const FETCH_LOGIN_SUCCESS= 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILED= 'FETCH_LOGIN_FAILED'