// list friends
export const FETCH_LIST_FRIEND= 'FETCH_LIST_FRIEND';
export const FETCH_LIST_FRIEND_SUCCESS= 'FETCH_LIST_FRIEND_SUCCESS'
export const FETCH_LIST_FRIEND_FAILED= 'FETCH_LIST_FRIEND_FAILED'