// list conversation
export const FETCH_LIST_CONVERSATION = "FETCH_LIST_CONVERSATION";
export const FETCH_LIST_CONVERSATION_SUCCESS ="FETCH_LIST_CONVERSATION_SUCCESS";
export const FETCH_LIST_CONVERSATION_FAILED = "FETCH_LIST_CONVERSATION_FAILED";
// list message
export const FETCH_LIST_MESSAGE= "FETCH_LIST_MESSAGE";
export const FETCH_LIST_MESSAGE_SUCCESS= "FETCH_LIST_MESSAGE_SUCCESS";
export const FETCH_LIST_MESSAGE_FAILED= "FETCH_LIST_MESSAGE_FAILED";
